# Generated by Django 4.2.7 on 2025-10-04 16:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('model_type', models.CharField(choices=[('colorectal_normal_vs_cancer', 'Colorectal Normal vs Cancer'), ('colorectal_subtype', 'Colorectal Cancer Subtype'), ('lung_cancer', 'Lung Cancer Classification')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=50)),
                ('metric_value', models.CharField(max_length=20)),
                ('metric_description', models.TextField()),
                ('analysis_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='classification.analysissession')),
            ],
            options={
                'db_table': 'model_performance',
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('normal_vs_cancer', 'Normal vs Cancer'), ('subtype', 'Cancer Subtype'), ('lung_cancer_classification', 'Lung Cancer Classification')], max_length=50)),
                ('class_label', models.CharField(max_length=100)),
                ('probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence_score', models.FloatField(default=0.0)),
                ('analysis_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='classification.analysissession')),
            ],
            options={
                'db_table': 'classification_results',
                'ordering': ['-probability'],
            },
        ),
        migrations.AddField(
            model_name='analysissession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to='classification.patient'),
        ),
    ]
